### ISSUE TITLE
Remove large-scale flow U(t) from BarotropicQG

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#135]
I'm tempted to remove the large-scale flow from BarotropicQG as it's too specific and makes the code hard to penetrate for first-time users. Perhaps move U(t) functionality in an example or a different module...

**Comment by glwagner** [comment]
alternatively you can make `sol` a `NamedTuple` and optionally activate `U(t)` evolution if `sol.U` isn't `nothing`

**Comment by navidcy** [comment]
@glwagner, I feel that https://github.com/FourierFlows/FourierFlows.jl/issues/212 should be dealt first. Then what you suggest would be smoother.
