### ISSUE TITLE
Add 1.5-layer QG functionality

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#137]
It's easy to include a finite Rossby deformation radius in BarotropicQG module. I vote first to clear up `BarotropicQG` module as implied by #135 and then modify the BarotropicQG module to add such functionality.

pinging @liasiegelman as she's interested and could help us out here.

**Comment by liasiegelman** [comment]
sounds good to me. I will let you know as soon as my barotropicQG with kdef implemented in the streamfunction runs smoothly

**Comment by navidcy** [comment]
@liasiegelman, [v0.9.0](https://github.com/FourierFlows/GeophysicalFlows.jl/releases/tag/v0.9.0) includes a cleaner `BarotropicQG` module. Feel free to make a PR modifying it to include finite Rossby radius of deformation.

Perhaps we should change the module's name since it won't be purely barotropic then? What about `OneLayerQG`?

cc @glwagner

**Comment by liasiegelman** [comment]
Thanks @navidcy, will do. What about equivalentbarotropicQG for the name?

**Comment by glwagner** [comment]
OneLayer is probably better than Barotropic anyways! EquivalentBarotropicQG seems good too.

**Comment by navidcy** [comment]
Does `EquivalentBarotropicQG` includes the purely barotropic case `k_deformation=0`? If so then it's good name. Otherwise let's go with `OneLayerQG` or `SingleLayerQG`.

**Comment by liasiegelman** [comment]
ah yes then it's just barotropic so probably better to stick with your original suggestion.

**Comment by glwagner** [comment]
"SingleLayer" might be a better complement to "Multilayer" (eg with "OneLayer" we might want "NLayer").
