### ISSUE TITLE
SurfaceQG not defined

### ISSUE THREAD

**Issue by codenameatcg** [FourierFlows/GeophysicalFlows.jl#144]
?

![image](https://user-images.githubusercontent.com/74340419/99940195-a7ebc680-2da6-11eb-846b-1c96818524e6.png)

**Comment by navidcy** [comment]
can you printout the output of 
```julia
] st
```
?

**Comment by codenameatcg** [comment]
> can you printout the output of
> 
> ```julia
> ] st
> ```
> 
> ?

![image](https://user-images.githubusercontent.com/74340419/100021843-13707b00-2e1d-11eb-92eb-066f06bc11c2.png)

**Comment by navidcy** [comment]
Seems you have GeophysicalFlows.jl v0.5.2; `SurfaceQG` module was added at the v0.8.0.

Could you try:
```julia
] up FourierFlows GeophysicalFlows
```

**Comment by codenameatcg** [comment]
> Seems you have GeophysicalFlows.jl v0.5.2; `SurfaceQG` module was added at version 0.8.0.
> 
> Could you try:
> 
> ```julia
> ] up FourierFlows GeophysicalFlows
> ```

still.
![image](https://user-images.githubusercontent.com/74340419/100301653-92a7af80-2fd3-11eb-8428-14488b63c0fc.png)

![geofp](https://user-images.githubusercontent.com/74340419/100301471-29c03780-2fd3-11eb-81c4-d77ccbeb8fb0.png)

![fourierflows](https://user-images.githubusercontent.com/74340419/100301492-3775bd00-2fd3-11eb-9098-ee39a4c9007e.png)

**Comment by navidcy** [comment]
After you called
```Julia
]up FourierFlows GeophysicalFlows
```
did the packages actually updated? I don't see anything happened... An 
```Julia
]st
```
afterwards would reveal what version of GeophysicalFlows you have...

You can always try
```Julia
]add GeophysicalFlows@v0.8.4
```
which will try to install the particular version and, hopefully, will give you some informative error which you can share if it can't do it. :)

**Comment by codenameatcg** [comment]
even worse

![image](https://user-images.githubusercontent.com/74340419/100306446-60e81600-2fde-11eb-8a6d-0fb6b7b41cee.png)

**Comment by navidcy** [comment]
There is, apparently, some conflict with package compat requirement with some of the rest of the packages you have installed.

You may consider instantiating GeophysicalFlows in a Project on its own together with Pluto and anything else you need. Perhaps [this](https://docs.julialang.org/en/v1/stdlib/Pkg/) is a good starting point?

**Comment by navidcy** [comment]
I can help you out doing so. Please don't be sad --> your emoji :(

**Comment by glwagner** [comment]
dependency hell is hell indeed
