### ISSUE TITLE
Move GPU tests from gitlab to buildkite?

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#146]
Should we do this, what you reckon @glwagner? (Same for FourierFlows.jl btw...)

cc @maleadt, @vchuravy

**Comment by vchuravy** [comment]
:+1: I think @maleadt is thinking of eventually deprecating the Gitlab one.

**Comment by navidcy** [comment]
> a Buildkite administrator needs to request installation of the app, for which he needs to be part of the GitHub organization. The request then needs to be accepted by an owner of the GitHub organization (organization settings > installed GitHub Apps > Pending GitHub Apps installation requests).

So what's the process for doing so? Chat with either of you?

**Comment by maleadt** [comment]
> So, @vchuravy, what's the process for doing so? Chat with either of you?

Yes. Happy to help, just contact me on Slack.
