### ISSUE TITLE
Questions on `linear rotating shallow water dynamics` example

### ISSUE THREAD

**Issue by randomwangran** [FourierFlows/GeophysicalFlows.jl#172]
Dear maintainers of `GeophysicalFlows.jl`:

I was wondering that if some further explanations can be added to
some of the examples, which can be understood by the general
public.

For example, [linear rotating shallow water dynamics](https://fourierflows.github.io/FourierFlowsDocumentation/stable/generated/OneDShallowWaterGeostrophicAdjustment/#Linear-rotating-shallow-water-dynamics) documents how
the PDEs are formulated. I am trying to understand these equations
by real-world example.

If a glass is half-filled with water, and I can somehow rotate this
glass within its symmetrical line with a constant angular velocity,
are those PDEs still remain valid?

Thank you

**Comment by navidcy** [comment]
@randomwangran, when we wrote down the "Linear shallow water equations" we were mostly thinking of them in a geophysical setting, e.g., as that described in [chapter 4 in Vallis' book](http://empslocal.ex.ac.uk/people/staff/gv219/essence/essence-sample.pdf). Thus, the `f` parameter is Coriolis, i.e., the component of the Earth's rotation vector normal to the plane of motion. In summary, there are some extra assumptions made given the relevant scales of motions (e.g., in ocean and atmosphere vertical scales are much shorter than horizontal scales, etc) and this results in the equations simplifying and taking the "shallow water" form.

I believe that to describe the rotating glass with water problem you need to simply rewrite the Navier-Stokes equations in a rotating frame of reference. But if you do that, then you will end up with much more terms that the shallow water dynamics (e.g., centrifugal force term).

Is this clear/clearer now? Do you feel a clarification is in order at the Docs example?

**Comment by randomwangran** [comment]
Thanks for the clarification on the shallow water topic @navidcy. The
beautiful book by GEOFFREY K. VALLIS' book explains well on this
topic. I now have a much better understanding of this topic.

I agree with you on my poor example given.

On page 64 of the reference book, I find why my example is invalid
for the shallow water assumption.

> The key assumption underlying the shallow water equations is that of a
> small aspect ratio, so that H/L ≪ 1, where H is the ﬂuid depth and L
> the horizontal scale of motion.

I can now play with your code to see how shallow water works.
Thanks for your time and comments.

**Comment by navidcy** [comment]
@randomwangran, I'd suggest you check out GeophysicalFlows.jl also ;)

**Comment by navidcy** [comment]
We do have plans (or better say ambition at this point) for 2D nonlinear shallow water dynamics (see #163).
