### ISSUE TITLE
Sign error in SingleLayerQG Docs

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#194]
I think the vortex stretching term in `SingeLayerQG` includes the minus sign, right?
If so, we should fix this:
https://github.com/FourierFlows/GeophysicalFlows.jl/blob/9e114c6c835dff42a30e84d0d247f1e7ec9d61cf/docs/src/modules/singlelayerqg.md#L12-L13

**Comment by liasiegelman** [comment]
@navidcy agreed
