### ISSUE TITLE
modules should come with their docs

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#2]

**Comment by glwagner** [comment]
Agree in principle, but there is precedent for the "develop first, document later" strategy...

I think a natural workflow is to develop a code, start using it for research, and then as things are running and in a stable place start to update the docs. In early phases when we are still trying to decide what things are called (is it `energy00` or `Uenergy`?) it saves time to put off doc-writing.

Also, putting off doc-writing gives us the chance to return to the code and look over it a second time... ?

**Comment by navidcy** [comment]
There is some miscommunication here.
What I meant is when we move modules from `FourierFlows.jl` here then we should move their modest documentation from `FourierFlows.jl`.

Other than that I totally agree.

**Comment by glwagner** [comment]
As far as I can tell, the module documentation was ported from FourierFlows to GeophysicalFlows.

For example, [here is the TwoDTurb documentation](https://fourierflows.github.io/GeophysicalFlows.jl/latest/modules/twodturb.html).

What am I missing?
