### ISSUE TITLE
Cannot load v0.3 via Pkg

### ISSUE THREAD

**Issue by dkarrasch** [FourierFlows/GeophysicalFlows.jl#22]
When I simply try to `]add GeophysicalFlows`, I am getting delivered version 0.2.0. Is that a problem on my end, or is it related to registering/tagging etc.? Usually, when a package has a `Project.toml`, you're not supposed to have a `REQUIRE` file, but this one has both. I can put my package status in here if that's necessary, but wanted to quickly check if that issue has an "easy fix" without digging into all depencies installed in my Julia.

**Comment by dkarrasch** [comment]
It seems that the latest version has not been registered in the Julia registry:
https://github.com/JuliaRegistries/General/blob/master/G/GeophysicalFlows/Versions.toml
I guess you will need to install the [Registrator](https://github.com/JuliaRegistries/Registrator.jl) first, and then tag manually or by the TagBot. Anyway, it would be very helpful if users got delivered the latest stable version, without needing to check out master.

**Comment by navidcy** [comment]
Hm... @dkarrasch I believe I did exactly what you suggest here.
Does it take a few days for packages to appear in Julia registry? Version 0.3.0 was tagged only few days ago..

**Comment by dkarrasch** [comment]
Haha, I was typing a long message while you edited yours. You seem to have found everything.

Great package, by the way. I'm collaborating with @natschil with whom you already had contact.

**Comment by dkarrasch** [comment]
I think, what you can do, after installing the registrator app, is to call it from right here and register the current version, which the registrator will find in the `Project.toml` anyway.

**Comment by navidcy** [comment]
#23 fixes this; I'm closing the issue.

Thanks for your nice remarks!
