### ISSUE TITLE
Potential missing factor in `MultiLayerQG.energies`

### ISSUE THREAD

**Issue by apaloczy** [FourierFlows/GeophysicalFlows.jl#292]
I think there may be a missing `1 / sum(params.H)` factor in the potential energies part of `MultiLayerQG.energies`.

This is because in the n-layer case, multiplying the PV equations by $\psi_n H_n/H$ (with $H = \Sigma H_n$) and adding them together to form the energy equation gives potential energy terms that look like

$$\mathrm{PE_{j+1/2}} = \frac{1}{2} \frac{f_0^2}{g_{j+1/2}'H} \iint (\psi_j - \psi_{j+1})^2 \frac{dx dy}{Lx Ly}.$$

The total energy is nearly conserved as expected in two-layer decaying turbulence simulations if the `1 / sum(params.H)` is added.

Does this check? If so, I can open a pull request.

**Comment by navidcy** [comment]
This check! Open a PR please!
