### ISSUE TITLE
Should we be passing `forcing_spectrum` as argument into `calcF!`?

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#299]
At the moment, in the examples with stochastic forcing the `calcF!` function knows the `forcing_spectrum` as a global variable. 

https://github.com/FourierFlows/GeophysicalFlows.jl/blob/e15f1fb4964afbe4d67d9b55d23000106f777fdc/examples/twodnavierstokes_stochasticforcing.jl#L60-L82

Does this slows down the code? Should we be passing it as, e.g., a parameter argument?

E.g.,

```Julia
 function calcF!(Fh, sol, t, clock, vars, params, grid, p)
   Fh .= sqrt.(p.forcing_spectrum) .* exp.(2π * im * random_uniform(eltype(grid), size(sol))) / sqrt(clock.dt) 
    
   return nothing 
 end 

```

cc @glwagner

**Comment by glwagner** [comment]
I'd be surprised if the code is slower in this case, but one can test. Global variables can produce performance issues if the global variable appears within an inner loop. Here the variable is an array, it's only the _elements_ of the array that appear in a loop. Another solution is to make it a constant via `const forcing_spectrum = ...` .

**Comment by navidcy** [comment]
Seems like it doesn't matter

```Julia
function calcF!(Fh, sol, t, clock, vars, params, grid)
  T = eltype(grid)
  @. Fh = sqrt(forcing_spectrum) * cis(2π * random_uniform(T)) / sqrt(clock.dt)

  return nothing
end
nothing # hide

function calcF_passing_forcing_spectrum!(Fh, sol, t, clock, vars, params, grid, forcing_spectrum)
  T = eltype(grid)
  @. Fh = sqrt(forcing_spectrum) * cis(2π * random_uniform(T)) / sqrt(clock.dt)
  
  return nothing
end

julia> @btime calcF!(Fh, sol, t, clock, vars, params, grid)
  154.500 μs (14 allocations: 384 bytes)

julia> @btime calcF_passing_forcing_spectrum!(Fh, sol, t, clock, vars, params, grid, forcing_spectrum)
  154.500 μs (13 allocations: 368 bytes)
```
