### ISSUE TITLE
Forcing in TwoDTurb is not correct

### ISSUE THREAD

**Issue by glwagner** [FourierFlows/GeophysicalFlows.jl#3]
This implementation of forcing is only valid either for forcing that is constant in time, or only changes at the beginning of a time-step:

**https://github.com/FourierFlows/GeophysicalFlows.jl/blob/master/src/twodturb.jl#L191**

This implementation is not valid for forcing functions that change smoothly in time. In that case, `calcF!` must be called and the forcing added to the nonlinear term `N` each time that `calcN!` is called --- not only on 'substeps'.

I'm worried that correcting this will break some tests involving stochastic budgets. @navidcy, can you fix it? Are there similar issues elsewhere?

The trickiness involving substeps occurs for stochastic forcing, in which the forcing needs to be calculated only at the beginning of a whole timestep (and should not change during the substeps).

I propose that we write some code to help users implement stochastic forcing and add this to FourierFlows. I'm not sure exactly what this should look like, but I think it should somehow help the user avoid having to put `if t==s.t` statements in their forcing function, and also store `prevsol` automatically.

**Comment by glwagner** [comment]
The issue is that, if the forcing were implemented more generally (no `if` statement qualifying when `calcF` is called), a user could correctly implement both smoothly-varying and stochastic forcing without modifying the source code if they understand the numerics (by including their own `if` statement in the `calcF` they prescribe, and by storing `prevsol`).

But as currently implemented, it is not possible for the user to implement a smoothly-varying forcing without modifying the source code.

**Comment by navidcy** [comment]
Agree. I think I have a resolution to that. Let’s talk about it.

**Comment by navidcy** [comment]
PR #4 resolves the issue

**Comment by navidcy** [comment]
PR #6 fixes forcing implementation in `BarotropicQG` module.

I'm closing the issue.
