### ISSUE TITLE
@reexport using FourierFlows in GeophysicalFlows.jl?

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#33]
Why don't we call this
https://github.com/FourierFlows/GeophysicalFlows.jl/blob/c3c4f2d42b9f05f68c6cbfccd1043729eb511357/src/barotropicqg.jl#L16-L18
inside GeophysicalFlows.jl and instead we call it inside each module?

**Comment by glwagner** [comment]
The question is whether users will typically write 

using GeophysicalFlows

Or 

using GeophysicalFlows.ModuleOfInterest

But maybe you have a point that it’s better to encourage “using GeophysicalFlows”, and then enforce the pattern “prob = TwoDTurb.Problem(...)”

**Comment by navidcy** [comment]
OK, I'm closing for now..

**Comment by navidcy** [comment]
This issue is been brought back to the frontline inspired by @pdebuyl's remark in [JOSS paper review](https://github.com/openjournals/joss-reviews/issues/3053#issuecomment-818964253).

A more streamlined approach to help users is to have `GeophysicalFlows.jl` re-export all functionality in `FourierFlows.jl`.

**Comment by glwagner** [comment]
Agree.
