### ISSUE TITLE
Tag a new version and remove Manifest.toml?

### ISSUE THREAD

**Issue by dkarrasch** [FourierFlows/GeophysicalFlows.jl#35]
The latest tagged version seems to have issues on Julia v1.3, which are resolved on `master`:
```julia
GeophysicalFlows.peakedisotropicspectrum(mygrid, 2, 0.5)
MethodError: no method matching abs2(::Array{Complex{Float64},0})
Closest candidates are:
  abs2(!Matched::SymEngine.Basic) at /Users/karrasch/.julia/packages/SymEngine/zSUGO/src/mathfuns.jl:62
  abs2(!Matched::Missing) at missing.jl:100
  abs2(!Matched::Bool) at bool.jl:84
  ...
```
 So, I'd like to kindly request that you tag a new version unless you have some hot stuff that you want to get in first.

Also, I wanted to ask why you put the `Manifest.toml` in here? IIUC, the way to put compatibility bounds on dependencies is via the `compat` section in the `Project.toml`. Maybe, you could remove the `Manifest` and see what the latest versions of your dependencies are? Also, having a `Manifest.toml` seems to "restrict" basically all the packages in the dependency tree. I'd suggest to have lower bounds on your direct dependencies, and then leave to `Pkg` figuring out which subdependencies to use. If I can help with anything, let me know.

**Comment by navidcy** [comment]
@glwagner, I think @dkarrasch is right about ditching the `Manifest.toml` from the package (actually also from [FourierFlows.jl](https://github.com/FourierFlows/FourierFlows.jl)). I don't remember why we put it there in the first place. Possibly bad understanding of `.toml` file usage?
What do you think?

**Comment by glwagner** [comment]
I'm certainly fine with this. Seems some popular packages also omit `Manifest.toml`.

**Comment by navidcy** [comment]
@dkarrasch, sorry for taking so long
Could you workaround that using, e.g.,
```julia
]add GeophysicalFlows#master

We are indeed in the middle of converting all modules to run smoothly on GPUs before we proceed to making another release.

**Comment by navidcy** [comment]
@dkarrasch, I just tagged v0.3.1 #46
