### ISSUE TITLE
Add Pudig & Smith 2024 in the papers list

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#362]
We should add this in the list of papers that use the package

https://essopenarchive.org/users/788821/articles/1121326-baroclinic-turbulence-above-rough-topography-the-vortex-gas-and-topographic-turbulence-regimes?commit=97d9089a22b5921316486999b3dd46a0bf714a0d

Could you open a PR @mpudig?

**Comment by mpudig** [comment]
@navidcy Sorry for the slow uptake – I was on holidays and away from my computer. Thanks very much for adding our paper!
