### ISSUE TITLE
Chan-type forcing

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#5]
@glwagner: I'm very tempted to ditch this example. How do you feel about that?

https://github.com/FourierFlows/GeophysicalFlows.jl/blob/15b04e68106483f00b9114fdcffe3f023705e404/examples/twodturb_constantforcing.jl#L1-L94

**Comment by glwagner** [comment]
Do it. Let's have a minimum number of examples for now. Later if it is needed we can create a "tutorial" for a certain version of the code (still, not included in the repository).

**Comment by navidcy** [comment]
Moved it to (private) repo `navidcy/FourierFlows-sandbox`.
