### ISSUE TITLE
Docs are making repo size huuuge?

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#76]
I just cloned the repo and it's 500MB... I think the .pngs and .mp4 files in the docs (and potentially others) are making the repo size large.

This reminds me of the [issue in Oceananigans.jl](https://github.com/CliMA/Oceananigans.jl/issues/509), which btw is still ongoing... :( few days ago the Oceananigans.jl repo was ~300MB :(

**Comment by glwagner** [comment]
yuge

**Comment by navidcy** [comment]
@glwagner, @ali-ramadhan

note the use of `withenv` in the `docs/make.jl` if you want Documenter.jl to deploy the docs in a different repository:
 https://github.com/FourierFlows/GeophysicalFlows.jl/blob/8f34068af6a0ae289c3eb2d753de307a88c8672f/docs/make.jl#L92-L97
