### ISSUE TITLE
error message: multilayerqg_2layer.jl

### ISSUE THREAD

**Issue by cctsien** [FourierFlows/GeophysicalFlows.jl#91]
Hi, 

I tried to follow the example of multilayerqg_2layer.jl and encountered the following error message:

> # ## Problem setup
> # We initialize a `Problem` by providing a set of keyword arguments,
> prob = MultilayerQG.Problem(nlayers, dev; nx=nx, Lx=Lx, f0=f0, g=g, H=H, ρ=ρ, U=U, dt=dt, stepper=stepper, μ=μ, β=β)
> nothing # hide

```
MethodError: no method matching zeros(::Int64, ::CPU, ::Tuple{Int64,Int64})
Closest candidates are:
  zeros(!Matched::CPU, ::Any, ::Any) at /Users/XXX/.julia/packages/FourierFlows/Xyzjv/src/utils.jl:76
  zeros(!Matched::Union{Integer, AbstractUnitRange}...) at array.jl:499

Stacktrace:
 [1] top-level scope at In[14]:1
```

Not sure how to solve this... 

Best, 🍊

**Comment by navidcy** [comment]
Could you report which version of GeophysicalFlows are you using?

**Comment by navidcy** [comment]
@cctsien there was indeed a bug. I fixed it and released a new version. You should be fine on GeophysicalFlows **v0.5.1**
