### ISSUE TITLE
Random number generator: cpu/gpu

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/GeophysicalFlows.jl#97]
If `dev=GPU()` I think what this does is that it creates random numbers on CPU and transfers then to GPU
https://github.com/FourierFlows/GeophysicalFlows.jl/blob/de360d79a3c1ca3a663cc4aa855db222f9c820b3/examples/barotropicqg_betaforced.jl#L72
Is this true? If so, we want to be creating the random numbers on the GPU itself, e.g.,
```julia
Random.rand(CURAND.default_rng(), Float32, 1)
```
?

**Comment by glwagner** [comment]
Yes definitely. When this example was written, random number generators on the GPU were not available. Let's update it.

**Comment by navidcy** [comment]
Closed by #225.
